apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-sidecar
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  nginx-sidecar
  template:
    metadata:
      labels:
        app:  nginx-sidecar
    spec:
      shareProcessNamespace: true
      containers:
      - image: nginx:1.23.3-alpine
        name: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config
        imagePullPolicy: IfNotPresent
      - image: docker.io/deeplythink/nginx-reloader:v1
        name: nginx-sidecar
        env:
        - name: WATCH_NGINX_CONF_PATH
          value: /etc/nginx/conf.d
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config
        imagePullPolicy: Always
      volumes:
        - name: config
          configMap:
            name: nginx-sidecar
